// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB;
using LinqToDB.Data;

#pragma warning disable 1573, 1591
#nullable enable

namespace DataModel
{
	public partial class BabynamesDb : DataConnection
	{
		public BabynamesDb()
		{
			InitDataContext();
		}

		public BabynamesDb(string configuration)
			: base(configuration)
		{
			InitDataContext();
		}

		public BabynamesDb(DataOptions<BabynamesDb> options)
			: base(options.Options)
		{
			InitDataContext();
		}

		partial void InitDataContext();

		public ITable<Babyname> Babynames => this.GetTable<Babyname>();
	}
}
