// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;

#pragma warning disable 1573, 1591
#nullable enable

namespace DataModel
{
	[Table("Babynames")]
	public class Babyname
	{
		[Column("Name" , CanBeNull = false)] public string Name  { get; set; } = null!; // TEXT
		[Column("Year"                    )] public long   Year  { get; set; } // INTEGER
		[Column("Sex"  , CanBeNull = false)] public string Sex   { get; set; } = null!; // TEXT
		[Column("Count"                   )] public long   Count { get; set; } // INTEGER
	}
}
