// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB;
using LinqToDB.Async;
using LinqToDB.Data;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;

#pragma warning disable 1573, 1591
#nullable enable

namespace DataModel
{
	public partial class WorldCitiesDB : DataConnection
	{
		public WorldCitiesDB()
		{
			InitDataContext();
		}

		public WorldCitiesDB(string configuration)
			: base(configuration)
		{
			InitDataContext();
		}

		public WorldCitiesDB(DataOptions options)
			: base(options)
		{
			InitDataContext();
		}

		partial void InitDataContext();

		public ITable<Worldcity> Worldcities => this.GetTable<Worldcity>();
	}

	public static partial class ExtensionMethods
	{
		#region Table Extensions
		public static Worldcity? Find(this ITable<Worldcity> table, long? ogcFid)
		{
			return table.FirstOrDefault(e => e.OgcFid == ogcFid);
		}

		public static Task<Worldcity?> FindAsync(this ITable<Worldcity> table, long? ogcFid, CancellationToken cancellationToken = default)
		{
			return table.FirstOrDefaultAsync(e => e.OgcFid == ogcFid, cancellationToken);
		}
		#endregion
	}
}
